[base]
id = 1
name = "arceos"
vm_type = 1
cpu_num = 1
phys_cpu_sets = [1]

[kernel]
entry_point = 0x9000_0000
image_location = "fs"
kernel_path = "arceos-loongarch64.elf"
kernel_load_addr = 0x9000_0000
memory_regions = [
    [0x9000_0000, 0x100_0000, 0x7, 0],
    [0x8000_0000, 0x1000_0000, 0x7, 0]
]

[devices]
passthrough_devices = [
    ["loongson_intc@1fe00000", 0x1fe0_0000, 0x1fe0_0000, 0x1000, 0x1],
    ["loongson_uart@1fe001e0", 0x1fe0_01e0, 0x1fe0_01e0, 0x20, 0x1],
    ["virtio_mmio", 0xa00_0000, 0xa00_0000, 0x4000, 0x1]
]